### ISSUE TITLE
상품 디테일 페이지

### ISSUE THREAD

**Issue by miso062** [miso062/TeamProject_BitCamp#84]

**Comment by miso062** [comment]
2명이 같이 하기

**Comment by miso062** [comment]
은지, 수정

**Comment by sudong1004** [comment]
header, Container1, Container2, footer

**Comment by sudong1004** [comment]
![image](https://user-images.githubusercontent.com/104674992/177713449-adcb5db3-1ec8-4818-a342-e2b47210b94a.png)

**Comment by sudong1004** [comment]
![image](https://user-images.githubusercontent.com/104674992/177713570-17aed426-9b8d-4b5e-9bf6-9ab835950aba.png)

구매/ 판매 버튼 안보일 때 헤더 생성
